// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class ACTIVITEdto
    {
        public string CodeActivite { get; set; }
        public string LibelleActivite { get; set; }
    }
}