// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class BORDEREAUdto
    {
        public string NumeroBordereau { get; set; }
        public DateTime DateBordereau { get; set; }
        public string CodePeriode { get; set; }
        public string CodeEmploye { get; set; }
        public string CodeRubrique { get; set; }
        public string CodePlan { get; set; }
        public decimal Valeur { get; set; }

        public virtual EMPLOYEdto CodeEmployeNavigation { get; set; }
        public virtual PLAN_PAIE_DETAILdto CodeP { get; set; }
    }
}