// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class DECLARATION_CNSS_TAUX_EMPLOYEURdto
    {
        public string CodeEmploye { get; set; }
        public DateTime DateDebut { get; set; }
        public DateTime DateFin { get; set; }
        public decimal TauxCotisationEmployeur { get; set; }
        public decimal TauxAccidentTravail { get; set; }

        public virtual EMPLOYEdto CodeEmployeNavigation { get; set; }
    }
}