// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class DECLARATION_EMPLOYEURdto
    {
        public int? Annee { get; set; }
        public string CodeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public string CIN { get; set; }
        public string MatriculeEmploye { get; set; }
        public string MatriculeSecuriteSociale { get; set; }
        public string CodeFonction { get; set; }
        public string LibelleFonction { get; set; }
        public string Adresse { get; set; }
        public string SituationFamilliale { get; set; }
        public decimal? NombreMois { get; set; }
        public decimal? Imposable { get; set; }
        public decimal? Deduction { get; set; }
        public decimal? Impot { get; set; }
        public decimal? RedevanceCompensation { get; set; }
        public decimal? Net { get; set; }
    }
}