// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class EMPLOYE_VENTILATIONdto
    {
        public string CodeEmploye { get; set; }
        public string CodeActivite { get; set; }
        public string CodeDepartement { get; set; }
        public string CodeFonction { get; set; }
        public decimal Coefficient { get; set; }
    }
}