// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class EMPLOYEdto
    {
        public EMPLOYEdto()
        {
            BORDEREAU = new HashSet<BORDEREAUdto>();
            BULLETIN_PAIE = new HashSet<BULLETIN_PAIEdto>();
            DECLARATION_CNSS_DETAIL = new HashSet<DECLARATION_CNSS_DETAILdto>();
            DECLARATION_CNSS_TAUX_EMPLOYEUR = new HashSet<DECLARATION_CNSS_TAUX_EMPLOYEURdto>();
            EMPLOYE_ABSENCE = new HashSet<EMPLOYE_ABSENCEdto>();
            EMPLOYE_AJUSTEMENT_CONGE = new HashSet<EMPLOYE_AJUSTEMENT_CONGEdto>();
            EMPLOYE_AVANCE = new HashSet<EMPLOYE_AVANCEdto>();
            EMPLOYE_A_CHARGE = new HashSet<EMPLOYE_A_CHARGEdto>();
            EMPLOYE_CONGE = new HashSet<EMPLOYE_CONGEdto>();
            EMPLOYE_CONTRAT = new HashSet<EMPLOYE_CONTRATdto>();
            EMPLOYE_CORRESPONDANCE = new HashSet<EMPLOYE_CORRESPONDANCEdto>();
            EMPLOYE_DEDUCTION = new HashSet<EMPLOYE_DEDUCTIONdto>();
            EMPLOYE_DISCIPLINE = new HashSet<EMPLOYE_DISCIPLINEdto>();
            EMPLOYE_DOCUMENT = new HashSet<EMPLOYE_DOCUMENTdto>();
            EMPLOYE_FORMATION = new HashSet<EMPLOYE_FORMATIONdto>();
            EMPLOYE_OBSERVATION = new HashSet<EMPLOYE_OBSERVATIONdto>();
            EMPLOYE_PRET = new HashSet<EMPLOYE_PRETdto>();
            EMPLOYE_RUBRIQUE = new HashSet<EMPLOYE_RUBRIQUEdto>();
            POINTAGE = new HashSet<POINTAGEdto>();
            VIREMENT_DETAIL = new HashSet<VIREMENT_DETAILdto>();
        }

        public string CodeEmploye { get; set; }
        public string MatriculeEmploye { get; set; }
        public string CodeAppellation { get; set; }
        public string NomEmploye { get; set; }
        public string CIN { get; set; }
        public DateTime DateCIN { get; set; }
        public string Passeport { get; set; }
        public DateTime DatePasseport { get; set; }
        public DateTime DateEntree { get; set; }
        public DateTime? DateSortie { get; set; }
        public string CodeFonction { get; set; }
        public string CodeDepartement { get; set; }
        public decimal SalaireBase { get; set; }
        public decimal TauxHoraire { get; set; }
        public string CodeGrille { get; set; }
        public string CodeSituation { get; set; }
        public DateTime? DateSituation { get; set; }
        public bool ChefFamille { get; set; }
        public decimal CongeAnnuel { get; set; }
        public decimal CongeAnterieur { get; set; }
        public string MatriculeSecuriteSociale { get; set; }
        public string MatriculeAssuranceGroupe { get; set; }
        public string NumeroPermisConduite { get; set; }
        public string CodeModePaiement { get; set; }
        public string CodeBanque { get; set; }
        public string AgenceBanque { get; set; }
        public string RIB { get; set; }
        public DateTime DateNaissance { get; set; }
        public string LieuNaissance { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string CodePostal { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string AdresseMail { get; set; }
        public string Nationalite { get; set; }
        public byte[] PhotoEmploye { get; set; }
        public int TaillePhoto { get; set; }
        public string CodeOperateur { get; set; }
        public DateTime DateModification { get; set; }
        public string CodePlan { get; set; }
        public string Notes { get; set; }
        public string CodeNaturePaiement { get; set; }
        public decimal TauxJournalier { get; set; }
        public bool Imposable { get; set; }
        public bool CotisationSociale { get; set; }
        public bool AssuranceGroupe { get; set; }
        public bool ImpotLiquidatif { get; set; }
        public bool Smig { get; set; }
        public bool RedevanceCompensation { get; set; }
        public decimal MontantPlafondAssuranceGroupe { get; set; }
        public decimal ImposableAnterieur { get; set; }
        public decimal ImpotAnterieur { get; set; }
        public string AnneeImpotAnterieur { get; set; }
        public bool Cavis { get; set; }
        public string Suffixe { get; set; }
        public int SituationFamilialle { get; set; }

        public virtual USERdto USER { get; set; }
        public virtual ICollection<BORDEREAUdto> BORDEREAU { get; set; }
        public virtual ICollection<BULLETIN_PAIEdto> BULLETIN_PAIE { get; set; }
        public virtual ICollection<DECLARATION_CNSS_DETAILdto> DECLARATION_CNSS_DETAIL { get; set; }
        public virtual ICollection<DECLARATION_CNSS_TAUX_EMPLOYEURdto> DECLARATION_CNSS_TAUX_EMPLOYEUR { get; set; }
        public virtual ICollection<EMPLOYE_ABSENCEdto> EMPLOYE_ABSENCE { get; set; }
        public virtual ICollection<EMPLOYE_AJUSTEMENT_CONGEdto> EMPLOYE_AJUSTEMENT_CONGE { get; set; }
        public virtual ICollection<EMPLOYE_AVANCEdto> EMPLOYE_AVANCE { get; set; }
        public virtual ICollection<EMPLOYE_A_CHARGEdto> EMPLOYE_A_CHARGE { get; set; }
        public virtual ICollection<EMPLOYE_CONGEdto> EMPLOYE_CONGE { get; set; }
        public virtual ICollection<EMPLOYE_CONTRATdto> EMPLOYE_CONTRAT { get; set; }
        public virtual ICollection<EMPLOYE_CORRESPONDANCEdto> EMPLOYE_CORRESPONDANCE { get; set; }
        public virtual ICollection<EMPLOYE_DEDUCTIONdto> EMPLOYE_DEDUCTION { get; set; }
        public virtual ICollection<EMPLOYE_DISCIPLINEdto> EMPLOYE_DISCIPLINE { get; set; }
        public virtual ICollection<EMPLOYE_DOCUMENTdto> EMPLOYE_DOCUMENT { get; set; }
        public virtual ICollection<EMPLOYE_FORMATIONdto> EMPLOYE_FORMATION { get; set; }
        public virtual ICollection<EMPLOYE_OBSERVATIONdto> EMPLOYE_OBSERVATION { get; set; }
        public virtual ICollection<EMPLOYE_PRETdto> EMPLOYE_PRET { get; set; }
        public virtual ICollection<EMPLOYE_RUBRIQUEdto> EMPLOYE_RUBRIQUE { get; set; }
        public virtual ICollection<POINTAGEdto> POINTAGE { get; set; }
        public virtual ICollection<VIREMENT_DETAILdto> VIREMENT_DETAIL { get; set; }
    }
}