// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class EMPLOYE_AFFICHAGE_GRILLEdto
    {
        public string CodeOperateur { get; set; }
        public string ColonneEmploye { get; set; }
        public short Ordre { get; set; }
        public short Largeur { get; set; }
    }
}