// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class EMPLOYE_OBSERVATIONdto
    {
        public string CodeObservation { get; set; }
        public string CodeEmploye { get; set; }
        public string ContenuObservation { get; set; }
        public DateTime DateObservation { get; set; }
        public string CodeOperateur { get; set; }
        public DateTime DateOperation { get; set; }

        public virtual EMPLOYEdto CodeEmployeNavigation { get; set; }
    }
}