// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class JOUR_FERIEdto
    {
        public long CodeJourFerie { get; set; }
        public string LibelleJourFerie { get; set; }
        public string DateJourFerie { get; set; }
        public string CodeOperateurJourFerie { get; set; }
        public DateTime DateOperationJourFerie { get; set; }
    }
}