// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class MODELE_CORRESPONDANCEdto
    {
        public MODELE_CORRESPONDANCEdto()
        {
            EMPLOYE_CORRESPONDANCE = new HashSet<EMPLOYE_CORRESPONDANCEdto>();
        }

        public string CodeDocument { get; set; }
        public string LibelleDocument { get; set; }
        public byte[] ModeleDocument { get; set; }
        public long TailleFichier { get; set; }

        public virtual ICollection<EMPLOYE_CORRESPONDANCEdto> EMPLOYE_CORRESPONDANCE { get; set; }
    }
}