// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class PLAN_PAIEdto
    {
        public PLAN_PAIEdto()
        {
            PLAN_PAIE_DETAIL = new HashSet<PLAN_PAIE_DETAILdto>();
        }

        public string CodePlan { get; set; }
        public string LibellePlan { get; set; }

        public virtual ICollection<PLAN_PAIE_DETAILdto> PLAN_PAIE_DETAIL { get; set; }
    }
}