// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using PersonnelASPnetCore.Domaine.Entities;
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class ROLEdto
    {
        public ROLEdto()
        {
            USER = new HashSet<USER>();
        }

        public string CodeRole { get; set; }
        public string Name { get; set; }

        public virtual ICollection<USER> USER { get; set; }
    }
}