// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class SITUATION_CONGE_SPECIALdto
    {
        public string CodeRubrique { get; set; }
        public string CodeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public string CodeDepartement { get; set; }
        public DateTime DateEntree { get; set; }
        public DateTime? DateSortie { get; set; }
        public string LibelleDepartement { get; set; }
        public string LibelleRubrique { get; set; }
        public decimal PlafondConge { get; set; }
        public decimal? CongePercuSpecial { get; set; }
    }
}