// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class TYPE_PRETdto
    {
        public TYPE_PRETdto()
        {
            EMPLOYE_PRET = new HashSet<EMPLOYE_PRETdto>();
        }

        public string CodeTypePret { get; set; }
        public string LibelleTypePret { get; set; }

        public virtual ICollection<EMPLOYE_PRETdto> EMPLOYE_PRET { get; set; }
    }
}