// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class TYPE_CONTRATdto
    {
        public TYPE_CONTRATdto()
        {
            EMPLOYE_CONTRAT = new HashSet<EMPLOYE_CONTRATdto>();
        }

        public string CodeTypeContrat { get; set; }
        public string LibelleTypeContrat { get; set; }

        public virtual ICollection<EMPLOYE_CONTRATdto> EMPLOYE_CONTRAT { get; set; }
    }
}