// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Dto.DTO
{
    public partial class USERdto
    {
        public string CodeUser { get; set; }
        public string CodeEmploye { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Connections { get; set; }
        public string MacAddress { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? ModifyDate { get; set; }
        public bool Status { get; set; }
        public string CodeRole { get; set; }
        public string AuthData { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public virtual EMPLOYEdto CodeEmployeNavigation { get; set; }
        public virtual ROLEdto CodeRoleNavigation { get; set; }
    }
}