// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class BAREME_SMIG
    {
        public decimal Montant1 { get; set; }
        public decimal Montant2 { get; set; }
        public decimal Taux { get; set; }
    }
}