// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class BORDEREAU
    {
        public string NumeroBordereau { get; set; }
        public DateTime DateBordereau { get; set; }
        public string CodePeriode { get; set; }
        public string CodeEmploye { get; set; }
        public string CodeRubrique { get; set; }
        public string CodePlan { get; set; }
        public decimal Valeur { get; set; }

        public virtual EMPLOYE CodeEmployeNavigation { get; set; }
        public virtual PLAN_PAIE_DETAIL CodeP { get; set; }
    }
}