// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class CONNECTIONS_HISTORY
    {
        public int Id { get; set; }
        public string CodeEmploye { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Role { get; set; }
        public int Connections { get; set; }
        public DateTime SignInDate { get; set; }
        public DateTime? SignOutDate { get; set; }
        public string Hostname { get; set; }
        public string MacAddress { get; set; }
        public string IpAddress { get; set; }

        public virtual USER CodeEmployeNavigation { get; set; }
        public virtual REFRESH_TOKEN IdNavigation { get; set; }
    }
}