// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class ECRITURE_DETAIL
    {
        public string NumeroEcriture { get; set; }
        public string NumeroCompteComptable { get; set; }
        public string LibelleEcriture { get; set; }
        public decimal MontantDebit { get; set; }
        public decimal MontantCredit { get; set; }
        public string Lettre { get; set; }

        public virtual ECRITURE NumeroEcritureNavigation { get; set; }
    }
}