// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class EMPLOYE_CORRESPONDANCE
    {
        public string CodeEmploye { get; set; }
        public string CodeDocument { get; set; }
        public string CodeDocumentModele { get; set; }
        public DateTime DateDocument { get; set; }
        public byte[] DocumentCorrespondance { get; set; }
        public long TailleFichier { get; set; }
        public string CodeOperateur { get; set; }
        public DateTime DateOperation { get; set; }

        public virtual MODELE_CORRESPONDANCE CodeDocumentModeleNavigation { get; set; }
        public virtual EMPLOYE CodeEmployeNavigation { get; set; }
    }
}