// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class EMPLOYE_AJUSTEMENT_CONGE
    {
        public string CodeAjustementConge { get; set; }
        public string CodeEmploye { get; set; }
        public DateTime DateAjustementConge { get; set; }
        public string LibelleAjustementConge { get; set; }
        public string DescriptionAjustementConge { get; set; }
        public byte NombreAjustement { get; set; }
        public string CodeOperateur { get; set; }
        public DateTime DateOperation { get; set; }

        public virtual EMPLOYE CodeEmployeNavigation { get; set; }
    }
}