// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class EMPLOYE_CONTRAT
    {
        public string CodeContratEmploye { get; set; }
        public string CodeEmploye { get; set; }
        public string CodeTypeContrat { get; set; }
        public DateTime DateDebutContrat { get; set; }
        public DateTime? DateFinContrat { get; set; }
        public DateTime? DateDebutPeriodeEssai { get; set; }
        public DateTime? DateFinPeriodeEssai { get; set; }
        public string CodeOperateur { get; set; }
        public DateTime DateOperation { get; set; }

        public virtual EMPLOYE CodeEmployeNavigation { get; set; }
        public virtual TYPE_CONTRAT CodeTypeContratNavigation { get; set; }
    }
}