// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class EMPLOYE_DISCIPLINE
    {
        public string CodeDiscipline { get; set; }
        public string CodeEmploye { get; set; }
        public string LibelleDiscipline { get; set; }
        public DateTime DateDiscipline { get; set; }
        public string DecisionDiscipline { get; set; }
        public string CodeOperateur { get; set; }
        public DateTime DateOperation { get; set; }

        public virtual EMPLOYE CodeEmployeNavigation { get; set; }
    }
}