// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class MODELE_CORRESPONDANCE
    {
        public MODELE_CORRESPONDANCE()
        {
            EMPLOYE_CORRESPONDANCE = new HashSet<EMPLOYE_CORRESPONDANCE>();
        }

        public string CodeDocument { get; set; }
        public string LibelleDocument { get; set; }
        public byte[] ModeleDocument { get; set; }
        public long TailleFichier { get; set; }

        public virtual ICollection<EMPLOYE_CORRESPONDANCE> EMPLOYE_CORRESPONDANCE { get; set; }
    }
}