// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class PARAMETRE_POINTAGE
    {
        public int ID { get; set; }
        public double NombreHeureSemaine { get; set; }
        public string RubriqueHeurePresenceNormale { get; set; }
        public string RubriqueHeureSupplementaire25 { get; set; }
        public double NombreHeureMax25 { get; set; }
        public string RubriqueHeureSupplementaire50 { get; set; }
        public string RubriqueJourFerie { get; set; }
        public string RubriqueDimanche { get; set; }
    }
}