// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class PLAN_PAIE
    {
        public PLAN_PAIE()
        {
            PLAN_PAIE_DETAIL = new HashSet<PLAN_PAIE_DETAIL>();
        }

        public string CodePlan { get; set; }
        public string LibellePlan { get; set; }

        public virtual ICollection<PLAN_PAIE_DETAIL> PLAN_PAIE_DETAIL { get; set; }
    }
}