// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class PLAN_PAIE_DETAIL
    {
        public PLAN_PAIE_DETAIL()
        {
            BORDEREAU = new HashSet<BORDEREAU>();
            BULLETIN_PAIE = new HashSet<BULLETIN_PAIE>();
        }

        public string CodePlan { get; set; }
        public string CodePeriode { get; set; }
        public string CodeTypePeriode { get; set; }
        public string LibellePeriode { get; set; }
        public int JourBase { get; set; }
        public int HeureBase { get; set; }
        public string DatePaye { get; set; }
        public string CodeModele { get; set; }

        public virtual MODELE_PAIE CodeModeleNavigation { get; set; }
        public virtual PLAN_PAIE CodePlanNavigation { get; set; }
        public virtual ICollection<BORDEREAU> BORDEREAU { get; set; }
        public virtual ICollection<BULLETIN_PAIE> BULLETIN_PAIE { get; set; }
    }
}