// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class SITE
    {
        public string CodeSite { get; set; }
        public string LibelleSite { get; set; }
    }
}