// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class TYPE_RUBRIQUE
    {
        public string CodeTypeRubrique { get; set; }
        public string LibelleOrigine { get; set; }
        public string LibelleTypeRubrique { get; set; }
    }
}