// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class TYPE_PRET
    {
        public TYPE_PRET()
        {
            EMPLOYE_PRET = new HashSet<EMPLOYE_PRET>();
        }

        public string CodeTypePret { get; set; }
        public string LibelleTypePret { get; set; }

        public virtual ICollection<EMPLOYE_PRET> EMPLOYE_PRET { get; set; }
    }
}