// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class VIREMENT
    {
        public VIREMENT()
        {
            VIREMENT_DETAIL = new HashSet<VIREMENT_DETAIL>();
        }

        public string NumeroVirement { get; set; }
        public DateTime DateVirement { get; set; }
        public string CodeBanqueVirement { get; set; }
        public decimal TotalVirement { get; set; }
        public string CodeBCT { get; set; }
        public int? CodeISO { get; set; }

        public virtual ICollection<VIREMENT_DETAIL> VIREMENT_DETAIL { get; set; }
    }
}