// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class Vue_CubeAnalysePaie
    {
        public string Id___Code { get; set; }
        public string Id___Matricule { get; set; }
        public string Id___Appellation { get; set; }
        public string Id___Nom_de_l_employé { get; set; }
        public string Id___CIN { get; set; }
        public DateTime? Id___CIN_Date { get; set; }
        public string Id___Passeport { get; set; }
        public string Id___Matricule_de_sécurité_sociale { get; set; }
        public string Id___Matricule_d_assurance_groupe { get; set; }
        public string Id___Numéro_du_permis { get; set; }
        public string Période___Libellé_de_la_période { get; set; }
        public DateTime Période___Date_de_paie { get; set; }
        public int? Période___Année_de_paie { get; set; }
        public string Période___Mois_de_paie { get; set; }
        public DateTime? Situation___Date_d_entrée { get; set; }
        public int? Situation___Année_d_entrée { get; set; }
        public int? Situation___Mois_d_entrée { get; set; }
        public DateTime? Situation___Date_de_sortie { get; set; }
        public string Situation___Année_de_sortie { get; set; }
        public string Situation___Mois_de_sortie { get; set; }
        public string Situation___Grille { get; set; }
        public string Situation___Situation_dans_la_grille { get; set; }
        public DateTime? Situation___Date_de_situation { get; set; }
        public string Situation___Année_de_situation { get; set; }
        public string Situation___Mois_de_situation { get; set; }
        public string Situation___Situation_familiale { get; set; }
        public int Situation___Nombre_d_enfants { get; set; }
        public string Situation___Type_de_contrat { get; set; }
        public string Affectation___Fonction { get; set; }
        public string Affectation___Département { get; set; }
        public string Salaire___Nature_de_paiement { get; set; }
        public decimal? Salaire___Taux_journalier { get; set; }
        public decimal? Salaire___Congé_annuel { get; set; }
        public decimal Salaire___Solde_de_congé { get; set; }
        public decimal? Salaire___Salaire_brut { get; set; }
        public decimal? Salaire___Cotisation_sociale { get; set; }
        public decimal? Salaire___Base_d_assurance_groupe { get; set; }
        public decimal? Salaire___Cotisation_d_assurance_groupe { get; set; }
        public decimal? Salaire___Imposable { get; set; }
        public decimal? Salaire___Impôt { get; set; }
        public decimal? Salaire___Salaire_net { get; set; }
        public decimal Salaire___Déductions_d_imposable { get; set; }
        public decimal Salaire___Montant_de_la_redevance_de_compensation { get; set; }
        public double? Salaire___Présence { get; set; }
        public double? Salaire___Absence { get; set; }
        public double? Salaire___Congé { get; set; }
        public decimal? Salaire___Remboursement_d_avances { get; set; }
        public decimal? Salaire___Remboursement_de_prêts { get; set; }
        public double? Salaire___Nombre_d_heures_supplémentaires { get; set; }
        public decimal? Salaire___Montant_d_heures_supplémentaires { get; set; }
        public string Paiement___Mode_de_paiement { get; set; }
        public string Paiement___Banque_de_l_employé { get; set; }
        public string Paiement___Agence_bancaire_de_l_employé { get; set; }
        public string Paiement___RIB_de_l_employé { get; set; }
        public DateTime? Informations___Date_de_naissance { get; set; }
        public string Informations___Année_de_naissance { get; set; }
        public string Informations___Mois_de_naissance { get; set; }
        public string Informations___Lieu_de_naissance { get; set; }
        public string Informations___Adresse { get; set; }
        public string Informations___Ville { get; set; }
        public string Informations___Code_postal { get; set; }
        public string Informations___Téléphone_1 { get; set; }
        public string Informations___Téléphone_2 { get; set; }
        public string Informations___EMail { get; set; }
        public string Informations___Nationalité { get; set; }
        public string Paramètres___Plan_de_paie { get; set; }
        public string Paramètres___Imposable { get; set; }
        public string Paramètres___Assujetti_à_la_cotisation_sociale { get; set; }
        public string Paramètres___Assujetti_à_l_assurance_groupe { get; set; }
        public string Paramètres___Assujetti_à_l_impôt_liquidatif { get; set; }
        public string Paramètres___SMIGARD { get; set; }
        public string Paramètres___Assujetti_à_la_redevance_de_compensation { get; set; }
        public string Paramètres___Adhérent_CAVIS { get; set; }
    }
}