// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace PersonnelASPnetCore.Domaine.Entities
{
    public partial class Vue_Mouvement_Conge_Special
    {
        public string CodeEmploye { get; set; }
        public string NumeroBulletin { get; set; }
        public DateTime DatePaye { get; set; }
        public string NomEmploye { get; set; }
        public string CodeDepartement { get; set; }
        public DateTime DateEntree { get; set; }
        public DateTime? DateSortie { get; set; }
        public string LibelleDepartement { get; set; }
        public string CodeRubrique { get; set; }
        public string LibelleRubrique { get; set; }
        public string CodeTypeRubrique { get; set; }
        public decimal PlafondConge { get; set; }
        public float? Nombre { get; set; }
    }
}