//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVANCEMENT_DETAIL
    {
        public string NumeroAvancement { get; set; }
        public string CodeEmploye { get; set; }
        public string CodeSituationAncien { get; set; }
        public System.DateTime DateSituationAncien { get; set; }
        public decimal SalaireBaseAncien { get; set; }
        public decimal TauxHoraireAncien { get; set; }
        public string MatriculeEmploye { get; set; }
        public string CodeFonction { get; set; }
        public string CodeDepartement { get; set; }
        public string CodeSituationNouveau { get; set; }
        public decimal SalaireBaseNouveau { get; set; }
        public decimal TauxHoraireNouveau { get; set; }
    }
}
