//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANQUE_VIREMENT
    {
        public string CodeBanqueVirement { get; set; }
        public string LibelleBanqueVirement { get; set; }
        public string AgenceBanqueVirement { get; set; }
        public string RIBBanqueVirement { get; set; }
        public string ContactBanqueVirement { get; set; }
        public string Adresse { get; set; }
        public string tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string NumeroCompteComptable { get; set; }
    }
}
