//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class BORDEREAU
    {
        public string NumeroBordereau { get; set; }
        public System.DateTime DateBordereau { get; set; }
        public string CodePeriode { get; set; }
        public string CodeEmploye { get; set; }
        public string CodeRubrique { get; set; }
        public string CodePlan { get; set; }
        public decimal Valeur { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
        public virtual PLAN_PAIE_DETAIL PLAN_PAIE_DETAIL { get; set; }
    }
}
