//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECLARATION_EMPLOYEUR
    {
        public Nullable<int> Annee { get; set; }
        public string CodeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public string CIN { get; set; }
        public string MatriculeEmploye { get; set; }
        public string MatriculeSecuriteSociale { get; set; }
        public string CodeFonction { get; set; }
        public string LibelleFonction { get; set; }
        public string Adresse { get; set; }
        public string SituationFamilliale { get; set; }
        public Nullable<decimal> NombreMois { get; set; }
        public Nullable<decimal> Imposable { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> Impot { get; set; }
        public Nullable<decimal> RedevanceCompensation { get; set; }
        public Nullable<decimal> Net { get; set; }
    }
}
