//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECLARATION_CNSS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DECLARATION_CNSS()
        {
            this.DECLARATION_CNSS_DETAIL = new HashSet<DECLARATION_CNSS_DETAIL>();
        }
    
        public int Annee { get; set; }
        public int Trimestre { get; set; }
        public System.DateTime DateDeclaration { get; set; }
        public bool Valide { get; set; }
        public string CodeOperateur { get; set; }
        public System.DateTime DateOperation { get; set; }
        public string ModePaiement { get; set; }
        public string NumeroCheque { get; set; }
        public string LibelleBanqueVirement { get; set; }
        public decimal Montant { get; set; }
        public string CodeBanqueVirement { get; set; }
        public string NumeroCompteComptable { get; set; }
        public decimal TauxSecurite { get; set; }
        public decimal TauxAccidentTravail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARATION_CNSS_DETAIL> DECLARATION_CNSS_DETAIL { get; set; }
    }
}
