//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECLARATION_CNSS_TAUX_EMPLOYEUR
    {
        public string CodeEmploye { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public decimal TauxCotisationEmployeur { get; set; }
        public decimal TauxAccidentTravail { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
    }
}
