//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECOMPTE_MONNAIE
    {
        public Nullable<int> Annee { get; set; }
        public Nullable<int> Mois { get; set; }
        public string CodeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public string MatriculeEmploye { get; set; }
        public Nullable<decimal> SalaireNet { get; set; }
        public Nullable<decimal> yMontant { get; set; }
        public Nullable<int> Nombre50D { get; set; }
        public Nullable<int> Nombre20D { get; set; }
        public Nullable<int> Nombre10D { get; set; }
        public Nullable<int> Nombre5D { get; set; }
        public Nullable<int> Nombre1D { get; set; }
        public Nullable<int> Nombre500M { get; set; }
        public Nullable<int> Nombre100M { get; set; }
        public Nullable<int> Nombre50M { get; set; }
        public Nullable<int> Nombre20M { get; set; }
        public Nullable<int> Nombre10M { get; set; }
        public Nullable<int> Residu { get; set; }
    }
}
