//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECRITURE_DETAIL
    {
        public string NumeroEcriture { get; set; }
        public string NumeroCompteComptable { get; set; }
        public string LibelleEcriture { get; set; }
        public decimal MontantDebit { get; set; }
        public decimal MontantCredit { get; set; }
        public string Lettre { get; set; }
    
        public virtual ECRITURE ECRITURE { get; set; }
    }
}
