//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECRITURE_OUVERTURE
    {
        public string NumeroCompteComptable { get; set; }
        public string LibelleCompteComptable { get; set; }
        public Nullable<decimal> MontantDebit { get; set; }
        public Nullable<decimal> MontantCredit { get; set; }
        public string NumeroEcritureOuverture { get; set; }
    
        public virtual COMPTE_COMPTABLE COMPTE_COMPTABLE { get; set; }
    }
}
