//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_AFFICHAGE_GRILLE
    {
        public string CodeOperateur { get; set; }
        public string ColonneEmploye { get; set; }
        public short Ordre { get; set; }
        public short Largeur { get; set; }
    }
}
