//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_DEDUCTION
    {
        public string CodeDeduction { get; set; }
        public string CodeEmploye { get; set; }
        public string LibelleDeduction { get; set; }
        public decimal MontantAnnuel { get; set; }
        public System.DateTime DateValidite { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
    }
}
