//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_CONTRAT
    {
        public string CodeContratEmploye { get; set; }
        public string CodeEmploye { get; set; }
        public string CodeTypeContrat { get; set; }
        public System.DateTime DateDebutContrat { get; set; }
        public Nullable<System.DateTime> DateFinContrat { get; set; }
        public Nullable<System.DateTime> DateDebutPeriodeEssai { get; set; }
        public Nullable<System.DateTime> DateFinPeriodeEssai { get; set; }
        public string CodeOperateur { get; set; }
        public System.DateTime DateOperation { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
        public virtual TYPE_CONTRAT TYPE_CONTRAT { get; set; }
    }
}
