//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_PRET
    {
        public string CodePret { get; set; }
        public string CodeEmploye { get; set; }
        public string LibellePret { get; set; }
        public string CodeTypePret { get; set; }
        public System.DateTime DateDemande { get; set; }
        public decimal MontantDemande { get; set; }
        public decimal MontantAccorde { get; set; }
        public System.DateTime DatePret { get; set; }
        public System.DateTime DateEffetPret { get; set; }
        public decimal Tranche { get; set; }
        public bool Actif { get; set; }
        public Nullable<System.DateTime> DateAcceptation { get; set; }
        public string MotifRefus { get; set; }
        public string Note { get; set; }
        public string CodeOperateur { get; set; }
        public System.DateTime DateOperation { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
        public virtual TYPE_PRET TYPE_PRET { get; set; }
    }
}
