//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_DOCUMENT
    {
        public string CodeDocument { get; set; }
        public string CodeEmploye { get; set; }
        public System.DateTime DateDocument { get; set; }
        public string CodeSecondaire { get; set; }
        public string TitreDocument { get; set; }
        public string ResumeDocument { get; set; }
        public string TexteDocument { get; set; }
        public string TypeDocument { get; set; }
        public byte[] ImageDocument { get; set; }
        public short Width { get; set; }
        public short Height { get; set; }
        public int TailleImageDocument { get; set; }
        public string CodeOperateur { get; set; }
        public System.DateTime DateOperation { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
    }
}
