//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_RUBRIQUE
    {
        public string CodeEmploye { get; set; }
        public string CodeRubrique { get; set; }
        public string CodeTypeRubrique { get; set; }
        public string LibelleRubrique { get; set; }
        public bool Actif { get; set; }
        public decimal MontantRubrique { get; set; }
        public decimal MontantPlafondMaximum { get; set; }
        public decimal MontantPlafondMinimum { get; set; }
        public string CodeTypeIndemnite { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
    }
}
