//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_FORMATION
    {
        public string CodeFormation { get; set; }
        public string CodeEmploye { get; set; }
        public string LibelleFormation { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public string LieuFormation { get; set; }
        public string Note { get; set; }
        public string CodeOperateur { get; set; }
        public System.DateTime DateOperation { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
    }
}
