//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYE()
        {
            this.BORDEREAU = new HashSet<BORDEREAU>();
            this.BULLETIN_PAIE = new HashSet<BULLETIN_PAIE>();
            this.DECLARATION_CNSS_DETAIL = new HashSet<DECLARATION_CNSS_DETAIL>();
            this.DECLARATION_CNSS_TAUX_EMPLOYEUR = new HashSet<DECLARATION_CNSS_TAUX_EMPLOYEUR>();
            this.EMPLOYE_A_CHARGE = new HashSet<EMPLOYE_A_CHARGE>();
            this.EMPLOYE_ABSENCE = new HashSet<EMPLOYE_ABSENCE>();
            this.EMPLOYE_AJUSTEMENT_CONGE = new HashSet<EMPLOYE_AJUSTEMENT_CONGE>();
            this.EMPLOYE_AVANCE = new HashSet<EMPLOYE_AVANCE>();
            this.EMPLOYE_CONGE = new HashSet<EMPLOYE_CONGE>();
            this.EMPLOYE_CONTRAT = new HashSet<EMPLOYE_CONTRAT>();
            this.EMPLOYE_CORRESPONDANCE = new HashSet<EMPLOYE_CORRESPONDANCE>();
            this.EMPLOYE_DEDUCTION = new HashSet<EMPLOYE_DEDUCTION>();
            this.EMPLOYE_DISCIPLINE = new HashSet<EMPLOYE_DISCIPLINE>();
            this.EMPLOYE_DOCUMENT = new HashSet<EMPLOYE_DOCUMENT>();
            this.EMPLOYE_FORMATION = new HashSet<EMPLOYE_FORMATION>();
            this.EMPLOYE_OBSERVATION = new HashSet<EMPLOYE_OBSERVATION>();
            this.EMPLOYE_PRET = new HashSet<EMPLOYE_PRET>();
            this.EMPLOYE_RUBRIQUE = new HashSet<EMPLOYE_RUBRIQUE>();
            this.POINTAGE = new HashSet<POINTAGE>();
            this.VIREMENT_DETAIL = new HashSet<VIREMENT_DETAIL>();
        }
    
        public string CodeEmploye { get; set; }
        public string MatriculeEmploye { get; set; }
        public string CodeAppellation { get; set; }
        public string NomEmploye { get; set; }
        public string CIN { get; set; }
        public System.DateTime DateCIN { get; set; }
        public string Passeport { get; set; }
        public System.DateTime DatePasseport { get; set; }
        public System.DateTime DateEntree { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public string CodeFonction { get; set; }
        public string CodeDepartement { get; set; }
        public decimal SalaireBase { get; set; }
        public decimal TauxHoraire { get; set; }
        public string CodeGrille { get; set; }
        public string CodeSituation { get; set; }
        public Nullable<System.DateTime> DateSituation { get; set; }
        public bool ChefFamille { get; set; }
        public decimal CongeAnnuel { get; set; }
        public decimal CongeAnterieur { get; set; }
        public string MatriculeSecuriteSociale { get; set; }
        public string MatriculeAssuranceGroupe { get; set; }
        public string NumeroPermisConduite { get; set; }
        public string CodeModePaiement { get; set; }
        public string CodeBanque { get; set; }
        public string AgenceBanque { get; set; }
        public string RIB { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public string LieuNaissance { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string CodePostal { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string AdresseMail { get; set; }
        public string Nationalite { get; set; }
        public byte[] PhotoEmploye { get; set; }
        public int TaillePhoto { get; set; }
        public string CodeOperateur { get; set; }
        public System.DateTime DateModification { get; set; }
        public string CodePlan { get; set; }
        public string Notes { get; set; }
        public string CodeNaturePaiement { get; set; }
        public decimal TauxJournalier { get; set; }
        public bool Imposable { get; set; }
        public bool CotisationSociale { get; set; }
        public bool AssuranceGroupe { get; set; }
        public bool ImpotLiquidatif { get; set; }
        public bool Smig { get; set; }
        public bool RedevanceCompensation { get; set; }
        public decimal MontantPlafondAssuranceGroupe { get; set; }
        public decimal ImposableAnterieur { get; set; }
        public decimal ImpotAnterieur { get; set; }
        public string AnneeImpotAnterieur { get; set; }
        public bool Cavis { get; set; }
        public string Suffixe { get; set; }
        public int SituationFamilialle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BORDEREAU> BORDEREAU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BULLETIN_PAIE> BULLETIN_PAIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARATION_CNSS_DETAIL> DECLARATION_CNSS_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARATION_CNSS_TAUX_EMPLOYEUR> DECLARATION_CNSS_TAUX_EMPLOYEUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_A_CHARGE> EMPLOYE_A_CHARGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_ABSENCE> EMPLOYE_ABSENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_AJUSTEMENT_CONGE> EMPLOYE_AJUSTEMENT_CONGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_AVANCE> EMPLOYE_AVANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_CONGE> EMPLOYE_CONGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_CONTRAT> EMPLOYE_CONTRAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_CORRESPONDANCE> EMPLOYE_CORRESPONDANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_DEDUCTION> EMPLOYE_DEDUCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_DISCIPLINE> EMPLOYE_DISCIPLINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_DOCUMENT> EMPLOYE_DOCUMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_FORMATION> EMPLOYE_FORMATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_OBSERVATION> EMPLOYE_OBSERVATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_PRET> EMPLOYE_PRET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYE_RUBRIQUE> EMPLOYE_RUBRIQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POINTAGE> POINTAGE { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIREMENT_DETAIL> VIREMENT_DETAIL { get; set; }
    }
}
