//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_CORRESPONDANCE
    {
        public string CodeEmploye { get; set; }
        public string CodeDocument { get; set; }
        public string CodeDocumentModele { get; set; }
        public System.DateTime DateDocument { get; set; }
        public byte[] DocumentCorrespondance { get; set; }
        public long TailleFichier { get; set; }
        public string CodeOperateur { get; set; }
        public System.DateTime DateOperation { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
        public virtual MODELE_CORRESPONDANCE MODELE_CORRESPONDANCE { get; set; }
    }
}
