//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_A_CHARGE
    {
        public string CodeEmploye { get; set; }
        public string CodePersonne { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Parente { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public Nullable<System.DateTime> DateLimite { get; set; }
        public byte[] PhotoPersonne { get; set; }
        public int TaillePhoto { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
    }
}
