//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_VENTILATION
    {
        public string CodeEmploye { get; set; }
        public string CodeActivite { get; set; }
        public string CodeDepartement { get; set; }
        public string CodeFonction { get; set; }
        public decimal Coefficient { get; set; }
    }
}
