//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE_CONGE
    {
        public string CodeConge { get; set; }
        public string CodeEmploye { get; set; }
        public string LibelleConge { get; set; }
        public System.DateTime DateDemande { get; set; }
        public System.DateTime DateDebutDemande { get; set; }
        public System.DateTime DateFinDemande { get; set; }
        public float NombreCongeDemande { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public float NombreConge { get; set; }
        public bool Actif { get; set; }
        public string MotifRefus { get; set; }
        public string Note { get; set; }
        public string CodeOperateur { get; set; }
        public System.DateTime DateOperation { get; set; }
        public string CodePeriode { get; set; }
        public int AnneeConge { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
    }
}
