//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grand_Livre
    {
        public string NumeroCompteComptable { get; set; }
        public string LibelleCompteComptable { get; set; }
        public string NumeroEcriture { get; set; }
        public System.DateTime DateEcriture { get; set; }
        public string LibelleEcriture { get; set; }
        public decimal MontantDebit { get; set; }
        public decimal MontantCredit { get; set; }
        public string Reference { get; set; }
        public string Origine { get; set; }
        public bool Valide { get; set; }
        public bool Ouverture { get; set; }
        public string CodeJournalComptable { get; set; }
        public string LibelleJournalComptable { get; set; }
        public string Lettre { get; set; }
    }
}
