//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_CAVIS
    {
        public string CodeEmploye { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<int> Trimestre { get; set; }
        public string MatriculeSecuriteSociale { get; set; }
        public string NomEmploye { get; set; }
        public string MatriculeEmploye { get; set; }
        public string CIN { get; set; }
        public System.DateTime DateEntree { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public Nullable<decimal> Mois1 { get; set; }
        public Nullable<decimal> Mois2 { get; set; }
        public Nullable<decimal> Mois3 { get; set; }
        public Nullable<decimal> TotalEmploye { get; set; }
    }
}
