//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_FICHE_ANNUELLE_PAIE
    {
        public Nullable<int> Annee { get; set; }
        public string CodeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public string MatriculeEmploye { get; set; }
        public string CodeDepartement { get; set; }
        public string LibelleDepartement { get; set; }
        public string CodeTypeRubrique { get; set; }
        public string CodeRubrique { get; set; }
        public string LibelleRubrique { get; set; }
        public Nullable<decimal> BaseJanvier { get; set; }
        public Nullable<decimal> BaseFevrier { get; set; }
        public Nullable<decimal> BaseMars { get; set; }
        public Nullable<decimal> BaseAvril { get; set; }
        public Nullable<decimal> BaseMai { get; set; }
        public Nullable<decimal> BaseJuin { get; set; }
        public Nullable<decimal> BaseJuillet { get; set; }
        public Nullable<decimal> BaseAout { get; set; }
        public Nullable<decimal> BaseSeptembre { get; set; }
        public Nullable<decimal> BaseOctobre { get; set; }
        public Nullable<decimal> BaseNovembre { get; set; }
        public Nullable<decimal> BaseDecembre { get; set; }
        public Nullable<decimal> BaseAnnuel { get; set; }
        public Nullable<decimal> NombreJanvier { get; set; }
        public Nullable<decimal> NombreFevrier { get; set; }
        public Nullable<decimal> NombreMars { get; set; }
        public Nullable<decimal> NombreAvril { get; set; }
        public Nullable<decimal> NombreMai { get; set; }
        public Nullable<decimal> NombreJuin { get; set; }
        public Nullable<decimal> NombreJuillet { get; set; }
        public Nullable<decimal> NombreAout { get; set; }
        public Nullable<decimal> NombreSeptembre { get; set; }
        public Nullable<decimal> NombreOctobre { get; set; }
        public Nullable<decimal> NombreNovembre { get; set; }
        public Nullable<decimal> NombreDecembre { get; set; }
        public Nullable<decimal> NombreAnnuel { get; set; }
        public Nullable<decimal> MontantJanvier { get; set; }
        public Nullable<decimal> MontantFevrier { get; set; }
        public Nullable<decimal> MontantMars { get; set; }
        public Nullable<decimal> MontantAvril { get; set; }
        public Nullable<decimal> MontantMai { get; set; }
        public Nullable<decimal> MontantJuin { get; set; }
        public Nullable<decimal> MontantJuillet { get; set; }
        public Nullable<decimal> MontantAout { get; set; }
        public Nullable<decimal> MontantSeptembre { get; set; }
        public Nullable<decimal> MontantOctobre { get; set; }
        public Nullable<decimal> MontantNovembre { get; set; }
        public Nullable<decimal> MontantDecembre { get; set; }
        public Nullable<decimal> MontantAnnuel { get; set; }
    }
}
