//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOUR_FERIE
    {
        public long CodeJourFerie { get; set; }
        public string LibelleJourFerie { get; set; }
        public string DateJourFerie { get; set; }
        public string CodeOperateurJourFerie { get; set; }
        public System.DateTime DateOperationJourFerie { get; set; }
    }
}
