//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTE_RAPPORT
    {
        public int IdImpression { get; set; }
        public string Module { get; set; }
        public string Impression { get; set; }
        public string LibelleImpression { get; set; }
        public string NomRapport { get; set; }
    }
}
