//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELE_PAIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODELE_PAIE()
        {
            this.BULLETIN_PAIE = new HashSet<BULLETIN_PAIE>();
            this.MODELE_PAIE_DETAIL = new HashSet<MODELE_PAIE_DETAIL>();
            this.PLAN_PAIE_DETAIL = new HashSet<PLAN_PAIE_DETAIL>();
        }
    
        public string CodeModele { get; set; }
        public string LibelleModele { get; set; }
        public bool InclurePret { get; set; }
        public bool InclureIndemnite { get; set; }
        public bool CalculLiquidatif { get; set; }
        public bool InclureAvance { get; set; }
        public string TitreBulletin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BULLETIN_PAIE> BULLETIN_PAIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODELE_PAIE_DETAIL> MODELE_PAIE_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAN_PAIE_DETAIL> PLAN_PAIE_DETAIL { get; set; }
    }
}
