//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRE_POINTAGE
    {
        public int ID { get; set; }
        public double NombreHeureSemaine { get; set; }
        public string RubriqueHeurePresenceNormale { get; set; }
        public string RubriqueHeureSupplementaire25 { get; set; }
        public double NombreHeureMax25 { get; set; }
        public string RubriqueHeureSupplementaire50 { get; set; }
        public string RubriqueJourFerie { get; set; }
        public string RubriqueDimanche { get; set; }
    }
}
