//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRE_COMPTABILITE
    {
        public string Groupe { get; set; }
        public string CodeParametre { get; set; }
        public string LibelleParametre { get; set; }
        public string ValeurParametre { get; set; }
    }
}
