//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class POINTAGE
    {
        public string NumeroPointage { get; set; }
        public System.DateTime DatePointage { get; set; }
        public string NumeroBordereau { get; set; }
        public string CodeEmploye { get; set; }
        public string DateJour { get; set; }
        public string CodeJour { get; set; }
        public string LibelleJour { get; set; }
        public string CodeSemaine { get; set; }
        public System.DateTime DateDebutPointage { get; set; }
        public System.DateTime DateFinPointage { get; set; }
        public decimal NombreHeure { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
    }
}
