//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFRESH_TOKEN
    {
        public int Id { get; set; }
        public string CodeEmploye { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedByIp { get; set; }
        public Nullable<System.DateTime> Revoked { get; set; }
        public string RevokedByIp { get; set; }
        public string ReplacedByToken { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual CONNECTIONS_HISTORY CONNECTIONS_HISTORY { get; set; }
        public virtual USER USER { get; set; }
    }
}
