//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBRIQUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RUBRIQUE()
        {
            this.MODELE_PAIE_DETAIL = new HashSet<MODELE_PAIE_DETAIL>();
        }
    
        public string CodeRubrique { get; set; }
        public string CodeTypeRubrique { get; set; }
        public string LibelleRubrique { get; set; }
        public decimal Taux { get; set; }
        public bool InclureAssuranceGroupe { get; set; }
        public bool InclureSecuriteSociale { get; set; }
        public bool InclureImpot { get; set; }
        public bool IndemniteActive { get; set; }
        public bool InclureIndemniteConge { get; set; }
        public string CodeTypeIndemnite { get; set; }
        public decimal MontantIndemnite { get; set; }
        public decimal BasePonderation { get; set; }
        public bool InclureBordereau { get; set; }
        public string TitreBordereau { get; set; }
        public bool RubriqueParDefaut { get; set; }
        public string NumeroCompteComptable { get; set; }
        public bool DetailComptecomptable { get; set; }
        public string SensCompteComptable { get; set; }
        public bool InclureCongeAnnuel { get; set; }
        public decimal PlafondConge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODELE_PAIE_DETAIL> MODELE_PAIE_DETAIL { get; set; }
    }
}
