//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEQUENCE
    {
        public string Annee { get; set; }
        public string TypeDocument { get; set; }
        public Nullable<short> Numero { get; set; }
        public bool RecupereNumero { get; set; }
    }
}
