//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SITUATION_CONGE
    {
        public string CodeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public string CodeDepartement { get; set; }
        public System.DateTime DateEntree { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public string LibelleDepartement { get; set; }
        public Nullable<decimal> CongeAnterieur { get; set; }
        public decimal CongeAnnuel { get; set; }
        public Nullable<decimal> PresenceAnnuelle { get; set; }
        public Nullable<decimal> PresenceDue { get; set; }
        public Nullable<decimal> PresenceEffective { get; set; }
        public Nullable<decimal> CongePercu { get; set; }
        public Nullable<decimal> DroitConge { get; set; }
        public Nullable<decimal> SoldeConge { get; set; }
    }
}
