//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_RUBRIQUE
    {
        public string CodeTypeRubrique { get; set; }
        public string LibelleOrigine { get; set; }
        public string LibelleTypeRubrique { get; set; }
    }
}
