//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CONNECTIONS_HISTORY = new HashSet<CONNECTIONS_HISTORY>();
            this.REFRESH_TOKEN = new HashSet<REFRESH_TOKEN>();
        }
    
        public string CodeEmploye { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Connections { get; set; }
        public string MacAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool Status { get; set; }
        public string CodeRole { get; set; }
        public string AuthData { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public string Token { get; set; }
        public string IpAddress { get; set; }
        public string AdresseMail { get; set; }
        public string Picture_URL { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<bool> IsAuthenticated { get; set; }
        public Nullable<bool> IsDisconnected { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONNECTIONS_HISTORY> CONNECTIONS_HISTORY { get; set; }
        public virtual EMPLOYE EMPLOYE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFRESH_TOKEN> REFRESH_TOKEN { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
