//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIREMENT_DETAIL
    {
        public string NumeroVirement { get; set; }
        public string NumeroBulletin { get; set; }
        public string CodePeriode { get; set; }
        public string CodeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public string CodeBanque { get; set; }
        public string AgenceBanque { get; set; }
        public string RIB { get; set; }
        public decimal Montant { get; set; }
    
        public virtual BULLETIN_PAIE BULLETIN_PAIE { get; set; }
        public virtual EMPLOYE EMPLOYE { get; set; }
        public virtual VIREMENT VIREMENT { get; set; }
    }
}
