//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIREMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VIREMENT()
        {
            this.VIREMENT_DETAIL = new HashSet<VIREMENT_DETAIL>();
        }
    
        public string NumeroVirement { get; set; }
        public System.DateTime DateVirement { get; set; }
        public string CodeBanqueVirement { get; set; }
        public decimal TotalVirement { get; set; }
        public string CodeBCT { get; set; }
        public Nullable<int> CodeISO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIREMENT_DETAIL> VIREMENT_DETAIL { get; set; }
    }
}
