//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vue_SituationPret
    {
        public string CodeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public string CodeDepartement { get; set; }
        public string LibelleDepartement { get; set; }
        public string CodePret { get; set; }
        public string LibellePret { get; set; }
        public string CodeTypePret { get; set; }
        public string LibelleTypePret { get; set; }
        public Nullable<System.DateTime> DateEffetPret { get; set; }
        public Nullable<decimal> MontantAccorde { get; set; }
        public Nullable<decimal> Tranche { get; set; }
        public Nullable<decimal> MontantRembourse { get; set; }
        public Nullable<decimal> MontantRestant { get; set; }
    }
}
