//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelASPnetCore.ModelEdmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vue_Mouvement_Conge
    {
        public string CodeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public string CodeDepartement { get; set; }
        public string LibelleDepartement { get; set; }
        public Nullable<decimal> CongeAnnuel { get; set; }
        public Nullable<int> TotalPresence { get; set; }
        public string NumeroMouvement { get; set; }
        public System.DateTime DateMouvement { get; set; }
        public Nullable<int> PresenceObligatoire { get; set; }
        public Nullable<double> Presence { get; set; }
        public Nullable<double> CongePercu { get; set; }
        public Nullable<decimal> DroitConge { get; set; }
    }
}
