// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDto.DTO
{
    public partial class APPELLATIONdto
    {
        public string CodeAppellation { get; set; }
        public string LibelleAppellation { get; set; }
    }
}