// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDto.DTO
{
    public partial class AVANCEMENTdto
    {
        public string NumeroAvancement { get; set; }
        public DateTime DateAvancement { get; set; }
        public DateTime DateOperation { get; set; }
        public bool Valide { get; set; }
    }
}