// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDto.DTO
{
    public partial class DEPARTEMENTdto
    {
        public DEPARTEMENTdto()
        {
            BULLETIN_PAIE = new HashSet<BULLETIN_PAIEdto>();
        }

        public string CodeDepartement { get; set; }
        public string LibelleDepartement { get; set; }

        public virtual ICollection<BULLETIN_PAIEdto> BULLETIN_PAIE { get; set; }
    }
}