// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDto.DTO
{
    public partial class EMPLOYE_A_CHARGEdto
    {
        public string CodeEmploye { get; set; }
        public string CodePersonne { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Parente { get; set; }
        public DateTime DateNaissance { get; set; }
        public DateTime? DateLimite { get; set; }
        public byte[] PhotoPersonne { get; set; }
        public int TaillePhoto { get; set; }

        public virtual EMPLOYEdto CodeEmployeNavigation { get; set; }
    }
}