// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDto.DTO
{
    public partial class EMPLOYE_CORRESPONDANCEdto
    {
        public string CodeEmploye { get; set; }
        public string CodeDocument { get; set; }
        public string CodeDocumentModele { get; set; }
        public DateTime DateDocument { get; set; }
        public byte[] DocumentCorrespondance { get; set; }
        public long TailleFichier { get; set; }
        public string CodeOperateur { get; set; }
        public DateTime DateOperation { get; set; }

        public virtual MODELE_CORRESPONDANCEdto CodeDocumentModeleNavigation { get; set; }
        public virtual EMPLOYEdto CodeEmployeNavigation { get; set; }
    }
}