// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDto.DTO
{
    public partial class GRILLEdto
    {
        public GRILLEdto()
        {
            GRILLE_DETAIL = new HashSet<GRILLE_DETAILdto>();
        }

        public string CodeGrille { get; set; }
        public string LibelleGrille { get; set; }

        public virtual ICollection<GRILLE_DETAILdto> GRILLE_DETAIL { get; set; }
    }
}