// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDto.DTO
{
    public partial class MODELE_PAIEdto
    {
        public MODELE_PAIEdto()
        {
            BULLETIN_PAIE = new HashSet<BULLETIN_PAIEdto>();
            MODELE_PAIE_DETAIL = new HashSet<MODELE_PAIE_DETAILdto>();
            PLAN_PAIE_DETAIL = new HashSet<PLAN_PAIE_DETAILdto>();
        }

        public string CodeModele { get; set; }
        public string LibelleModele { get; set; }
        public bool InclurePret { get; set; }
        public bool InclureIndemnite { get; set; }
        public bool CalculLiquidatif { get; set; }
        public bool InclureAvance { get; set; }
        public string TitreBulletin { get; set; }

        public virtual ICollection<BULLETIN_PAIEdto> BULLETIN_PAIE { get; set; }
        public virtual ICollection<MODELE_PAIE_DETAILdto> MODELE_PAIE_DETAIL { get; set; }
        public virtual ICollection<PLAN_PAIE_DETAILdto> PLAN_PAIE_DETAIL { get; set; }
    }
}