// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDto.DTO
{
    public partial class PARAMETRE_COMPTABILITEdto
    {
        public string Groupe { get; set; }
        public string CodeParametre { get; set; }
        public string LibelleParametre { get; set; }
        public string ValeurParametre { get; set; }
    }
}