// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDto.DTO
{
    public partial class PLAN_PAIE_DETAILdto
    {
        public PLAN_PAIE_DETAILdto()
        {
            BORDEREAU = new HashSet<BORDEREAUdto>();
            BULLETIN_PAIE = new HashSet<BULLETIN_PAIEdto>();
        }

        public string CodePlan { get; set; }
        public string CodePeriode { get; set; }
        public string CodeTypePeriode { get; set; }
        public string LibellePeriode { get; set; }
        public int JourBase { get; set; }
        public int HeureBase { get; set; }
        public string DatePaye { get; set; }
        public string CodeModele { get; set; }

        public virtual MODELE_PAIEdto CodeModeleNavigation { get; set; }
        public virtual PLAN_PAIEdto CodePlanNavigation { get; set; }
        public virtual ICollection<BORDEREAUdto> BORDEREAU { get; set; }
        public virtual ICollection<BULLETIN_PAIEdto> BULLETIN_PAIE { get; set; }
    }
}