// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDto.DTO
{
    public partial class TYPE_INDEMNITEdto
    {
        public string CodeTypeIndemnite { get; set; }
        public string LibelleTypeIndemnite { get; set; }
    }
}