USE [ARTIPERSONNEL_SOC001]
GO

UPDATE 
INSERT INTO [dbo].[ROLE] VALUES('R002','User')
INSERT INTO [dbo].[ROLE] VALUES('R003','Business Manager')	
INSERT INTO [dbo].[ROLE] VALUES('R004','Peintre')	
INSERT INTO [dbo].[ROLE] VALUES('R005','ASSISTANTE DIRECTION')	
INSERT INTO [dbo].[ROLE] VALUES('R006','MAINOEUVRE OCCASION')	
INSERT INTO [dbo].[ROLE] VALUES('R007','MONTEUR')	
INSERT INTO [dbo].[ROLE] VALUES('R008','MONTEUR OCCASIONNEL')	
INSERT INTO [dbo].[ROLE] VALUES('R009','OUVRIER')	
INSERT INTO [dbo].[ROLE] VALUES('R010','SECRETAIRE'	)
INSERT INTO [dbo].[ROLE] VALUES('R011','SOUDEUR')	
INSERT INTO [dbo].[ROLE] VALUES('R012','SOUDEUR QUALIFIE'	)
INSERT INTO [dbo].[ROLE] VALUES('R013','SUPERVISEUR QUALITE')	
INSERT INTO [dbo].[ROLE] VALUES('R014','TECHNIC COMMER')
INSERT INTO [dbo].[ROLE] VALUES('R015','TECHNICIEN'	)
INSERT INTO [dbo].[ROLE] VALUES('R016','CALORIFUGEUR'	)
INSERT INTO [dbo].[ROLE] VALUES('R017','TRACEUR QUALIFIE')	
INSERT INTO [dbo].[ROLE] VALUES('R018','AIDE CALORIFUGEUR')	
INSERT INTO [dbo].[ROLE] VALUES('R019','Responsable commerciale et achat')
INSERT INTO [dbo].[ROLE] VALUES('R020','Resp.Info et Logistique')	
INSERT INTO [dbo].[ROLE] VALUES('R021','Resp Administratif')
INSERT INTO [dbo].[ROLE] VALUES('R022','comptable & GRH')	
INSERT INTO [dbo].[ROLE] VALUES('R023','Superviseur HSSE')	
INSERT INTO [dbo].[ROLE] VALUES('R024','Apprenti'	)
INSERT INTO [dbo].[ROLE] VALUES('R025','CHAUFFEUR LIVREUR'	)
INSERT INTO [dbo].[ROLE] VALUES('R026','CHEFCHANTIER')	
INSERT INTO [dbo].[ROLE] VALUES('R027','ECHAFAUDEUR')	
INSERT INTO [dbo].[ROLE] VALUES('R028','ECHAFFAUDEUR')	
INSERT INTO [dbo].[ROLE] VALUES('R029','FEMME DE MENAGE')	
INSERT INTO [dbo].[ROLE] VALUES('R030','GARDIEN')	
INSERT INTO [dbo].[ROLE] VALUES('R031','GERANTE')	















SELECT * FROM [dbo].[ROLE]





--1		NULL
--2	User	NULL
--3	Business Manager	NULL
--4	Peintre	NULL
--5	ASSISTANTE DIRECTION	NULL
--6	MAINOEUVRE OCCASION	NULL
--7	MONTEUR	NULL
--8	MONTEUR OCCASIONNEL	NULL
--9	OUVRIER	NULL
--10	SECRETAIRE	NULL
--11	SOUDEUR	NULL
--12	SOUDEUR QUALIFIE	NULL
--13	SUPERVISEUR QUALITé	NULL
--14	TECHNIC COMMER	NULL
--15	TECHNICIEN	NULL
--16	CALORIFUGEUR	NULL
--17	TRACEUR QUALIFIE	NULL
--18	AIDE CALORIFUGEUR	NULL
--19	Responsable commerciale et achat	NULL
--20	Resp.Info et Logistique	NULL
--21	Resp Administratif, comptable & GRH	NULL
--22	Superviseur HSSE	NULL
--23	Apprenti	NULL
--24	CHAUFFEUR LIVREUR	NULL
--25	CHEFCHANTIER	NULL
--26	ECHAFAUDEUR	NULL
--27	ECHAFFAUDEUR	NULL
--28	FEMME DE MENAGE	NULL
--29	GARDIEN	NULL
--30	GERANTE	NULL
