// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class BANQUE_VIREMENT
    {
        public string CodeBanqueVirement { get; set; }
        public string LibelleBanqueVirement { get; set; }
        public string AgenceBanqueVirement { get; set; }
        public string RIBBanqueVirement { get; set; }
        public string ContactBanqueVirement { get; set; }
        public string Adresse { get; set; }
        public string tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string NumeroCompteComptable { get; set; }
    }
}