// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class DECLARATION_CNSS_TAUX_EMPLOYEUR
    {
        public string CodeEmploye { get; set; }
        public DateTime DateDebut { get; set; }
        public DateTime DateFin { get; set; }
        public decimal TauxCotisationEmployeur { get; set; }
        public decimal TauxAccidentTravail { get; set; }

        public virtual EMPLOYE CodeEmployeNavigation { get; set; }
    }
}