// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class ECRITURE
    {
        public ECRITURE()
        {
            ECRITURE_DETAIL = new HashSet<ECRITURE_DETAIL>();
        }

        public string NumeroEcriture { get; set; }
        public DateTime DateEcriture { get; set; }
        public string CodeJournalComptable { get; set; }
        public string Reference { get; set; }
        public string CodeUtilisateur { get; set; }
        public DateTime? DateSaisie { get; set; }
        public bool Valide { get; set; }
        public string Origine { get; set; }
        public string SousOrigine { get; set; }
        public bool Ouverture { get; set; }

        public virtual JOURNAL_COMPTABLE CodeJournalComptableNavigation { get; set; }
        public virtual ICollection<ECRITURE_DETAIL> ECRITURE_DETAIL { get; set; }
    }
}