// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class EMPLOYE_DEDUCTION
    {
        public string CodeDeduction { get; set; }
        public string CodeEmploye { get; set; }
        public string LibelleDeduction { get; set; }
        public decimal MontantAnnuel { get; set; }
        public DateTime DateValidite { get; set; }

        public virtual EMPLOYE CodeEmployeNavigation { get; set; }
    }
}