// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class EMPLOYE_VENTILATION
    {
        public string CodeEmploye { get; set; }
        public string CodeActivite { get; set; }
        public string CodeDepartement { get; set; }
        public string CodeFonction { get; set; }
        public decimal Coefficient { get; set; }
    }
}