// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class EMPLOYE_DOCUMENT
    {
        public string CodeDocument { get; set; }
        public string CodeEmploye { get; set; }
        public DateTime DateDocument { get; set; }
        public string CodeSecondaire { get; set; }
        public string TitreDocument { get; set; }
        public string ResumeDocument { get; set; }
        public string TexteDocument { get; set; }
        public string TypeDocument { get; set; }
        public byte[] ImageDocument { get; set; }
        public short Width { get; set; }
        public short Height { get; set; }
        public int TailleImageDocument { get; set; }
        public string CodeOperateur { get; set; }
        public DateTime DateOperation { get; set; }

        public virtual EMPLOYE CodeEmployeNavigation { get; set; }
    }
}