// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class GRILLE_DETAIL
    {
        public GRILLE_DETAIL()
        {
            BULLETIN_PAIE = new HashSet<BULLETIN_PAIE>();
        }

        public string CodeGrille { get; set; }
        public string CodeSituation { get; set; }
        public string LibelleSituation { get; set; }
        public decimal SalaireBase { get; set; }
        public decimal TauxHoraire { get; set; }
        public short DureeAnciennete { get; set; }

        public virtual GRILLE CodeGrilleNavigation { get; set; }
        public virtual ICollection<BULLETIN_PAIE> BULLETIN_PAIE { get; set; }
    }
}