// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class GRILLE
    {
        public GRILLE()
        {
            GRILLE_DETAIL = new HashSet<GRILLE_DETAIL>();
        }

        public string CodeGrille { get; set; }
        public string LibelleGrille { get; set; }

        public virtual ICollection<GRILLE_DETAIL> GRILLE_DETAIL { get; set; }
    }
}