// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class IMP_FICHE_ANNUELLE_PAIE
    {
        public int? Annee { get; set; }
        public string CodeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public string MatriculeEmploye { get; set; }
        public string CodeDepartement { get; set; }
        public string LibelleDepartement { get; set; }
        public string CodeTypeRubrique { get; set; }
        public string CodeRubrique { get; set; }
        public string LibelleRubrique { get; set; }
        public decimal? BaseJanvier { get; set; }
        public decimal? BaseFevrier { get; set; }
        public decimal? BaseMars { get; set; }
        public decimal? BaseAvril { get; set; }
        public decimal? BaseMai { get; set; }
        public decimal? BaseJuin { get; set; }
        public decimal? BaseJuillet { get; set; }
        public decimal? BaseAout { get; set; }
        public decimal? BaseSeptembre { get; set; }
        public decimal? BaseOctobre { get; set; }
        public decimal? BaseNovembre { get; set; }
        public decimal? BaseDecembre { get; set; }
        public decimal? BaseAnnuel { get; set; }
        public decimal? NombreJanvier { get; set; }
        public decimal? NombreFevrier { get; set; }
        public decimal? NombreMars { get; set; }
        public decimal? NombreAvril { get; set; }
        public decimal? NombreMai { get; set; }
        public decimal? NombreJuin { get; set; }
        public decimal? NombreJuillet { get; set; }
        public decimal? NombreAout { get; set; }
        public decimal? NombreSeptembre { get; set; }
        public decimal? NombreOctobre { get; set; }
        public decimal? NombreNovembre { get; set; }
        public decimal? NombreDecembre { get; set; }
        public decimal? NombreAnnuel { get; set; }
        public decimal? MontantJanvier { get; set; }
        public decimal? MontantFevrier { get; set; }
        public decimal? MontantMars { get; set; }
        public decimal? MontantAvril { get; set; }
        public decimal? MontantMai { get; set; }
        public decimal? MontantJuin { get; set; }
        public decimal? MontantJuillet { get; set; }
        public decimal? MontantAout { get; set; }
        public decimal? MontantSeptembre { get; set; }
        public decimal? MontantOctobre { get; set; }
        public decimal? MontantNovembre { get; set; }
        public decimal? MontantDecembre { get; set; }
        public decimal? MontantAnnuel { get; set; }
    }
}