// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class JOURNAL_COMPTABLE
    {
        public JOURNAL_COMPTABLE()
        {
            ECRITURE = new HashSet<ECRITURE>();
        }

        public string CodeJournalComptable { get; set; }
        public string LibelleJournalComptable { get; set; }
        public string NumeroCompteComptable { get; set; }

        public virtual ICollection<ECRITURE> ECRITURE { get; set; }
    }
}