// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class LISTE_RAPPORT
    {
        public int IdImpression { get; set; }
        public string Module { get; set; }
        public string Impression { get; set; }
        public string LibelleImpression { get; set; }
        public string NomRapport { get; set; }
    }
}