// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class MODELE_PAIE
    {
        public MODELE_PAIE()
        {
            BULLETIN_PAIE = new HashSet<BULLETIN_PAIE>();
            MODELE_PAIE_DETAIL = new HashSet<MODELE_PAIE_DETAIL>();
            PLAN_PAIE_DETAIL = new HashSet<PLAN_PAIE_DETAIL>();
        }

        public string CodeModele { get; set; }
        public string LibelleModele { get; set; }
        public bool InclurePret { get; set; }
        public bool InclureIndemnite { get; set; }
        public bool CalculLiquidatif { get; set; }
        public bool InclureAvance { get; set; }
        public string TitreBulletin { get; set; }

        public virtual ICollection<BULLETIN_PAIE> BULLETIN_PAIE { get; set; }
        public virtual ICollection<MODELE_PAIE_DETAIL> MODELE_PAIE_DETAIL { get; set; }
        public virtual ICollection<PLAN_PAIE_DETAIL> PLAN_PAIE_DETAIL { get; set; }
    }
}