// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class NATURE_PAIEMENT
    {
        public string CodeNaturePaiement { get; set; }
        public string LibelleNaturePaiement { get; set; }
    }
}