// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class REFRESH_TOKEN
    {
        public int Id { get; set; }
        public string CodeEmploye { get; set; }
        public string Token { get; set; }
        public DateTime? Expires { get; set; }
        public bool? IsExpired { get; set; }
        public DateTime Created { get; set; }
        public string CreatedByIp { get; set; }
        public DateTime? Revoked { get; set; }
        public string RevokedByIp { get; set; }
        public string ReplacedByToken { get; set; }
        public bool? IsActive { get; set; }

        public virtual USER CodeEmployeNavigation { get; set; }
        public virtual CONNECTIONS_HISTORY CONNECTIONS_HISTORY { get; set; }
    }
}