// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class SEQUENCE
    {
        public string Annee { get; set; }
        public string TypeDocument { get; set; }
        public short? Numero { get; set; }
        public bool? RecupereNumero { get; set; }
    }
}