// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class TYPE_CONTRAT
    {
        public TYPE_CONTRAT()
        {
            EMPLOYE_CONTRAT = new HashSet<EMPLOYE_CONTRAT>();
        }

        public string CodeTypeContrat { get; set; }
        public string LibelleTypeContrat { get; set; }

        public virtual ICollection<EMPLOYE_CONTRAT> EMPLOYE_CONTRAT { get; set; }
    }
}