// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class Vue_SoldeActuel_Conge
    {
        public string CodeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public string CodeDepartement { get; set; }
        public string LibelleDepartement { get; set; }
        public double? CongeAnterieur { get; set; }
        public decimal CongeAnnuel { get; set; }
        public int? PresenceAnnuelle { get; set; }
        public int? PresenceDue { get; set; }
        public double? PresenceEffective { get; set; }
        public double? CongePercu { get; set; }
        public decimal? DroitConge { get; set; }
        public decimal? SoldeConge { get; set; }
    }
}