// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADVICEDomaine.Entities
{
    public partial class Vue_Employe
    {
        public string CodeEmploye { get; set; }
        public string CodeAppellation { get; set; }
        public string LibelleAppellation { get; set; }
        public string MatriculeEmploye { get; set; }
        public string NomEmploye { get; set; }
        public string CIN { get; set; }
        public DateTime DateCIN { get; set; }
        public string Passeport { get; set; }
        public DateTime DatePasseport { get; set; }
        public string MatriculeSecuriteSociale { get; set; }
        public string MatriculeAssuranceGroupe { get; set; }
        public string NumeroPermisConduite { get; set; }
        public string CodeFonction { get; set; }
        public string LibelleFonction { get; set; }
        public string CodeDepartement { get; set; }
        public string LibelleDepartement { get; set; }
        public DateTime DateEntree { get; set; }
        public DateTime? DateSortie { get; set; }
        public string CodeGrille { get; set; }
        public string LibelleGrille { get; set; }
        public string CodeSituation { get; set; }
        public string LibelleSituation { get; set; }
        public DateTime? DateSituation { get; set; }
        public string CodePlan { get; set; }
        public string LibellePlan { get; set; }
        public decimal SalaireBase { get; set; }
        public string CodeNaturePaiement { get; set; }
        public string LibelleNaturePaiement { get; set; }
        public decimal TauxHoraire { get; set; }
        public decimal TauxJournalier { get; set; }
        public decimal CongeAnnuel { get; set; }
        public decimal CongeAnterieur { get; set; }
        public string CodeModePaiement { get; set; }
        public string LibelleModePaiement { get; set; }
        public string CodeBanque { get; set; }
        public string LibelleBanque { get; set; }
        public string AgenceBanque { get; set; }
        public string RIB { get; set; }
        public string Adresse { get; set; }
        public string CodePostal { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Ville { get; set; }
        public string AdresseMail { get; set; }
        public DateTime DateNaissance { get; set; }
        public string LieuNaissance { get; set; }
        public string Nationalite { get; set; }
        public string ChefFamille { get; set; }
        public int? EnfantACharge { get; set; }
        public int? ParentACharge { get; set; }
        public byte[] PhotoEmploye { get; set; }
        public DateTime DateModification { get; set; }
    }
}